# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1245, 736)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("hairstyle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		MainWindow.setStyleSheet("background-color: rgb(38, 40, 55);")
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout_21 = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout_21.setObjectName("gridLayout_21")
		self.gridLayout_2 = QtWidgets.QGridLayout()
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_2.setFont(font)
		self.label_2.setText("")
		self.label_2.setObjectName("label_2")
		self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_2, 1, 2, 1, 4)
		self.gridLayout_12 = QtWidgets.QGridLayout()
		self.gridLayout_12.setObjectName("gridLayout_12")
		self.label_camera2 = QtWidgets.QLabel(self.centralwidget)
		self.label_camera2.setStyleSheet("background-color: rgb(225, 225, 225);")
		self.label_camera2.setText("")
		self.label_camera2.setObjectName("label_camera2")
		self.gridLayout_12.addWidget(self.label_camera2, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_12, 3, 9, 6, 4)
		self.gridLayout = QtWidgets.QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.label = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(12)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout, 1, 1, 1, 1)
		self.gridLayout_5 = QtWidgets.QGridLayout()
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.gridLayout_21.addLayout(self.gridLayout_5, 13, 1, 1, 2)
		self.gridLayout_9 = QtWidgets.QGridLayout()
		self.gridLayout_9.setObjectName("gridLayout_9")
		self.gridLayout_21.addLayout(self.gridLayout_9, 13, 6, 1, 2)
		self.gridLayout_4 = QtWidgets.QGridLayout()
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.label_camera = QtWidgets.QLabel(self.centralwidget)
		self.label_camera.setStyleSheet("background-color: rgb(225, 225, 225);")
		self.label_camera.setText("")
		self.label_camera.setObjectName("label_camera")
		self.gridLayout_4.addWidget(self.label_camera, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_4, 3, 1, 9, 7)
		self.gridLayout_18 = QtWidgets.QGridLayout()
		self.gridLayout_18.setObjectName("gridLayout_18")
		self.label_12 = QtWidgets.QLabel(self.centralwidget)
		self.label_12.setStyleSheet("image: url(:/BGimage/target (2).png);")
		self.label_12.setText("")
		self.label_12.setObjectName("label_12")
		self.gridLayout_18.addWidget(self.label_12, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_18, 13, 9, 1, 1)
		self.gridLayout_19 = QtWidgets.QGridLayout()
		self.gridLayout_19.setObjectName("gridLayout_19")
		self.label_7 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(24)
		self.label_7.setFont(font)
		self.label_7.setAlignment(QtCore.Qt.AlignCenter)
		self.label_7.setObjectName("label_7")
		self.gridLayout_19.addWidget(self.label_7, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_19, 13, 10, 1, 2)
		self.line_7 = QtWidgets.QFrame(self.centralwidget)
		self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.gridLayout_21.addWidget(self.line_7, 12, 3, 1, 1)
		self.gridLayout_20 = QtWidgets.QGridLayout()
		self.gridLayout_20.setObjectName("gridLayout_20")
		self.label_9 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_9.setFont(font)
		self.label_9.setObjectName("label_9")
		self.gridLayout_20.addWidget(self.label_9, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_20, 13, 12, 1, 1)
		self.gridLayout_3 = QtWidgets.QGridLayout()
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.gridLayout_21.addLayout(self.gridLayout_3, 1, 6, 1, 2)
		self.gridLayout_17 = QtWidgets.QGridLayout()
		self.gridLayout_17.setObjectName("gridLayout_17")
		self.label_10 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Nirmala UI")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		self.label_10.setFont(font)
		self.label_10.setObjectName("label_10")
		self.gridLayout_17.addWidget(self.label_10, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_17, 11, 9, 1, 4)
		self.line = QtWidgets.QFrame(self.centralwidget)
		self.line.setFrameShape(QtWidgets.QFrame.VLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.gridLayout_21.addWidget(self.line, 3, 8, 1, 1)
		self.line_3 = QtWidgets.QFrame(self.centralwidget)
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.gridLayout_21.addWidget(self.line_3, 3, 13, 1, 1)
		self.line_4 = QtWidgets.QFrame(self.centralwidget)
		self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.gridLayout_21.addWidget(self.line_4, 2, 2, 1, 1)
		self.gridLayout_15 = QtWidgets.QGridLayout()
		self.gridLayout_15.setObjectName("gridLayout_15")
		self.label_6 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(24)
		self.label_6.setFont(font)
		self.label_6.setAlignment(QtCore.Qt.AlignCenter)
		self.label_6.setObjectName("label_6")
		self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_15, 10, 10, 1, 2)
		self.gridLayout_13 = QtWidgets.QGridLayout()
		self.gridLayout_13.setObjectName("gridLayout_13")
		self.label_8 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_8.setFont(font)
		self.label_8.setObjectName("label_8")
		self.gridLayout_13.addWidget(self.label_8, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_13, 10, 12, 1, 1)
		self.gridLayout_7 = QtWidgets.QGridLayout()
		self.gridLayout_7.setObjectName("gridLayout_7")
		self.playButton = QtWidgets.QPushButton(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
		self.playButton.setSizePolicy(sizePolicy)
		self.playButton.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.playButton.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.playButton.setIcon(icon1)
		self.playButton.setIconSize(QtCore.QSize(40, 40))
		self.playButton.setObjectName("playButton")
		self.gridLayout_7.addWidget(self.playButton, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_7, 13, 4, 1, 1)
		self.gridLayout_8 = QtWidgets.QGridLayout()
		self.gridLayout_8.setObjectName("gridLayout_8")
		self.stopButton = QtWidgets.QPushButton(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
		self.stopButton.setSizePolicy(sizePolicy)
		self.stopButton.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.stopButton.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.stopButton.setIcon(icon2)
		self.stopButton.setIconSize(QtCore.QSize(40, 40))
		self.stopButton.setObjectName("stopButton")
		self.gridLayout_8.addWidget(self.stopButton, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_8, 13, 5, 1, 1)
		self.gridLayout_14 = QtWidgets.QGridLayout()
		self.gridLayout_14.setObjectName("gridLayout_14")
		self.label_4 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Nirmala UI")
		font.setPointSize(16)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.gridLayout_14.addWidget(self.label_4, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_14, 9, 9, 1, 4)
		self.gridLayout_6 = QtWidgets.QGridLayout()
		self.gridLayout_6.setObjectName("gridLayout_6")
		self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
		self.pauseButton.setSizePolicy(sizePolicy)
		self.pauseButton.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.pauseButton.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pauseButton.setIcon(icon3)
		self.pauseButton.setIconSize(QtCore.QSize(40, 40))
		self.pauseButton.setObjectName("pauseButton")
		self.gridLayout_6.addWidget(self.pauseButton, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_6, 13, 3, 1, 1)
		self.gridLayout_16 = QtWidgets.QGridLayout()
		self.gridLayout_16.setObjectName("gridLayout_16")
		self.label_11 = QtWidgets.QLabel(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
		self.label_11.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(22)
		self.label_11.setFont(font)
		self.label_11.setStyleSheet("image: url(:/BGimage/epidermis.png);")
		self.label_11.setText("")
		self.label_11.setObjectName("label_11")
		self.gridLayout_16.addWidget(self.label_11, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_16, 10, 9, 1, 1)
		self.line_5 = QtWidgets.QFrame(self.centralwidget)
		self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.gridLayout_21.addWidget(self.line_5, 0, 2, 1, 1)
		self.line_2 = QtWidgets.QFrame(self.centralwidget)
		self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.gridLayout_21.addWidget(self.line_2, 1, 0, 1, 1)
		self.gridLayout_23 = QtWidgets.QGridLayout()
		self.gridLayout_23.setObjectName("gridLayout_23")
		self.label_time = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_time.setFont(font)
		self.label_time.setAlignment(QtCore.Qt.AlignCenter)
		self.label_time.setObjectName("label_time")
		self.gridLayout_23.addWidget(self.label_time, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_23, 1, 12, 1, 1)
		self.gridLayout_11 = QtWidgets.QGridLayout()
		self.gridLayout_11.setObjectName("gridLayout_11")
		self.label_date = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_date.setFont(font)
		self.label_date.setAlignment(QtCore.Qt.AlignCenter)
		self.label_date.setObjectName("label_date")
		self.gridLayout_11.addWidget(self.label_date, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_11, 1, 10, 1, 1)
		self.gridLayout_10 = QtWidgets.QGridLayout()
		self.gridLayout_10.setObjectName("gridLayout_10")
		self.label_13 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(12)
		self.label_13.setFont(font)
		self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_13.setObjectName("label_13")
		self.gridLayout_10.addWidget(self.label_13, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_10, 1, 9, 1, 1)
		self.gridLayout_22 = QtWidgets.QGridLayout()
		self.gridLayout_22.setObjectName("gridLayout_22")
		self.label_14 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_14.setFont(font)
		self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_14.setObjectName("label_14")
		self.gridLayout_22.addWidget(self.label_14, 0, 0, 1, 1)
		self.gridLayout_21.addLayout(self.gridLayout_22, 1, 11, 1, 1)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1245, 26))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">HN:</span></p></body></html>"))
		self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55ff7f;\">1000</span></p></body></html>"))
		self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">FUs</span></p></body></html>"))
		self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff007f;\">  Target Amount:</span></p></body></html>"))
		self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffff00;\">0</span></p></body></html>"))
		self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">FUs</span></p></body></html>"))
		self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00aaff;\">  Current Amount of Harvested Grafts: </span></p></body></html>"))
		self.label_time.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
		self.label_date.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
		self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Date:</span></p></body></html>"))
		self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Time:</span></p></body></html>"))

import resources_rc

if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

